// #define COMBO_ALLOW_ACTION_KEYS 
#define COMBO_VARIABLE_LEN

// #define LEADER_TIMEOUT    1000
#define TAPPING_TERM    200
#undef COMBO_TERM
#define COMBO_TERM    25

// Both?
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

// Per key?
#define TAPPING_FORCE_HOLD