#include QMK_KEYBOARD_H
// #include "g/keymap_combo.h"

#define _BASE 0 // default
#define _COLEMAK 1 // colemak
#define _NAV 2 // nav
#define _MOUSE 3 // mouse
#define _MEDIA 4 // media
#define _SYMBOL 5 // number
#define _SYMBOL_EXTRA 6 // number shift
#define _FUNC 7 // func

// force layer switch hold on all thumb LayerTap keys only
bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case LT(2,KC_BSPACE):
      return true;
    case LT(3,KC_TAB):
      return true;
    case LT(4,KC_ESCAPE):
      return true;
    case LT(5,KC_SPACE):
      return true;
    case LT(6,KC_ENTER):
      return true;
    case LT(7,KC_DELETE):
      return true;
    default:
      return false;
  }
}

// keymap
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT_gergoplex(

      KC_Q,KC_W,KC_E,KC_R,KC_T,
      KC_Y,KC_U,KC_I,KC_O,KC_P,

      LCTL_T(KC_A),LALT_T(KC_S),LGUI_T(KC_D),LSFT_T(KC_F),KC_G,
      KC_H,RSFT_T(KC_J),RGUI_T(KC_K),RALT_T(KC_L),RCTL_T(KC_QUOTE),

      LSFT_T(KC_Z),KC_X,KC_C,KC_V,KC_B,
      KC_N,KC_M,KC_COMMA,KC_DOT,RSFT_T(KC_SLASH),

      LT(4,KC_ESCAPE),LT(2,KC_BSPACE),LT(3,KC_TAB),
      LT(6,KC_ENTER),LT(5,KC_SPACE),LT(7,KC_DELETE)
    ),

  [_COLEMAK] = LAYOUT_gergoplex(

      KC_Q,KC_W,KC_F,KC_P,KC_B,
      KC_J,KC_L,KC_U,KC_Y,KC_QUOTE,

      LCTL_T(KC_A),LALT_T(KC_R),LGUI_T(KC_S),LSFT_T(KC_T),KC_G,
      KC_M,RSFT_T(KC_N),RGUI_T(KC_E),RALT_T(KC_I),RCTL_T(KC_O),

      LSFT_T(KC_Z),KC_X,KC_C,KC_D,KC_V,
      KC_K,KC_H,KC_COMMA,KC_DOT,RSFT_T(KC_SLASH),

      LT(4,KC_ESCAPE),LT(2,KC_BSPACE),LT(3,KC_TAB),
      LT(6,KC_ENTER),LT(5,KC_SPACE),LT(7,KC_DELETE)
    ),

  [_NAV] = LAYOUT_gergoplex(

      KC_1,KC_2,KC_3,KC_4,KC_5,
      KC_6,KC_7,KC_8,KC_9,KC_0,

      KC_LCTRL,KC_LALT,KC_LGUI,KC_LSHIFT,KC_GRAVE,
      KC_LEFT,KC_DOWN,KC_UP,KC_RIGHT,KC_SCOLON,

      LGUI(KC_Z),LGUI(KC_X),LGUI(KC_C),LGUI(KC_V),LGUI(LSFT(KC_Z)),
      KC_UNDERSCORE,KC_MINUS,KC_PLUS,KC_EQUAL,KC_BSLASH,

      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,
      KC_DOT,KC_SPACE,KC_DELETE
    ),

  [_MOUSE] = LAYOUT_gergoplex(

      KC_0,KC_9,KC_8,KC_7,KC_6,
      KC_TRANSPARENT,KC_UNDERSCORE,KC_DELETE,KC_GRAVE,KC_PIPE,

      KC_LCTRL,KC_LALT,KC_LGUI,KC_RSHIFT,KC_ENTER,
      KC_MS_LEFT,KC_MS_DOWN,KC_MS_UP,KC_MS_RIGHT,KC_COLON,

      KC_TRANSPARENT,KC_TRANSPARENT,KC_GRAVE,LGUI(KC_TAB),LGUI(KC_GRAVE),
      KC_MS_WH_LEFT,KC_MS_WH_DOWN,KC_MS_WH_UP,KC_MS_WH_RIGHT,KC_TRANSPARENT,

      KC_TRANSPARENT,KC_BSPACE,KC_TRANSPARENT,
      KC_MS_BTN2,KC_MS_BTN1,KC_MS_BTN3
    ),

  [_MEDIA] = LAYOUT_gergoplex(

      KC_AUDIO_VOL_UP,KC_AUDIO_MUTE,KC_UP,KC_TRANSPARENT,KC_TRANSPARENT,
      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,

      KC_AUDIO_VOL_DOWN,KC_LEFT,KC_DOWN,KC_RIGHT,KC_TRANSPARENT,
      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,

      KC_MEDIA_PLAY_PAUSE,KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT,KC_TRANSPARENT,
      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,

      KC_TRANSPARENT,KC_SPACE,KC_ENTER,
      KC_ENTER,KC_TRANSPARENT,KC_TRANSPARENT
    ),

  [_SYMBOL] = LAYOUT_gergoplex(

      KC_EXCLAIM,KC_AT,KC_HASH,KC_DOLLAR,KC_PERCENT,
      KC_CIRCUMFLEX,KC_AMPERSAND,KC_ASTERISK,KC_GRAVE,KC_PIPE,

      KC_LBRACKET,KC_RBRACKET,KC_LPRN,KC_RPRN,KC_TRANSPARENT,
      KC_HOME,KC_PGUP,KC_PGDOWN,KC_END,KC_QUOTE,

      KC_PERC,KC_DLR,KC_LCBR,KC_RCBR,KC_EXLM,
      KC_HASH,KC_MINUS,KC_PLUS,KC_CIRC,KC_BSLASH,

      KC_ESCAPE,KC_BSPACE,KC_TAB,
      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT
    ),

  [_SYMBOL_EXTRA] = LAYOUT_gergoplex(

      KC_TRANSPARENT,KC_TRANSPARENT,KC_ESCAPE,KC_TRANSPARENT,KC_TILDE,
      KC_TRANSPARENT,KC_UNDERSCORE,KC_TRANSPARENT,KC_TRANSPARENT,KC_PIPE,

      KC_CAPS,KC_PIPE,KC_CIRCUMFLEX,KC_TILDE,KC_TRANSPARENT,
      KC_TRANSPARENT,KC_RSHIFT,KC_RGUI,KC_RALT,KC_LCTRL,

      KC_TRANSPARENT,KC_TRANSPARENT,KC_GRAVE,KC_TRANSPARENT,KC_TRANSPARENT,
      KC_UNDERSCORE,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,

      KC_ESCAPE,KC_BSPACE,KC_TAB,
      KC_TRANSPARENT,KC_SPACE,KC_TRANSPARENT
    ),

  [_FUNC] = LAYOUT_gergoplex(

      KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,
      TO(0),TO(1),KC_TRANSPARENT,KC_TRANSPARENT,KC_BRIGHTNESS_UP,

      KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,
      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_BRIGHTNESS_DOWN,

      KC_F11,KC_F12,KC_F13,KC_F14,KC_F15,
      KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,

      KC_ESCAPE,KC_BSPACE,KC_TAB,
      KC_TRANSPARENT,KC_SPACE,KC_TRANSPARENT
    ),

};

